// Code generated by "stringer -type=MsgType"; DO NOT EDIT.

package xf

import "strconv"

const (
	_MsgType_name_0 = "CmdGetStateCmdWriteCmdStopWriteCmdResetCmdStartCmdStopCmdWakeupCmdResetWakeupCmdSetBeamCmdSetParamsCmdUploadLexiconCmdSendLogCmdSyncCmdStartSaveCmdStopSaveCmdBuildGrammarCmdUpdateLocalLexiconCmdStartThrowAudioCmdStopThrowAudioCmdResultValidationAckCmdCleanDialogHistoryCmdStartRecordCmdStopRecordCmdQuerySyncStatus"
	_MsgType_name_1 = "CmdCaeWriteDevinfoCmdCaeWriteEncrypt"
)

var (
	_MsgType_index_0 = [...]uint16{0, 11, 19, 31, 39, 47, 54, 63, 77, 87, 99, 115, 125, 132, 144, 155, 170, 191, 209, 226, 248, 269, 283, 296, 314}
	_MsgType_index_1 = [...]uint8{0, 18, 36}
)

func (i MsgType) String() string {
	switch {
	case 1 <= i && i <= 24:
		i -= 1
		return _MsgType_name_0[_MsgType_index_0[i]:_MsgType_index_0[i+1]]
	case 1000 <= i && i <= 1001:
		i -= 1000
		return _MsgType_name_1[_MsgType_index_1[i]:_MsgType_index_1[i+1]]
	default:
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
